### ISSUE TITLE
Visualization issue

### ISSUE THREAD

**Issue by Boom708** [yuxumin/PoinTr#12]
Could you provide the code of visualization for ShapeNet? Thank you very much.

**Comment by Boom708** [comment]
Sorry to bother you again. After I run the code as follows, there are only .log and config.yaml in the output file but no text file. Is there any other operation that needs to be done? Thanks.

bash ./scripts/test.sh 0 \
    --ckpts ./pretrained/PoinTr_PCN.pth \
    --config ./cfgs/PCN_models/PoinTr.yaml \
    --exp_name example

**Comment by yuxumin** [comment]
@Boom708 Hi, the code does not save the text file during test, but i think you can add a line into runner.py by yourself, maybe this [line](https://github.com/yuxumin/PoinTr/blob/master/tools/runner.py#L356), saving the dense prediction as a txt file, if you want to use Windows Meshlab as we do. Or you can try to use the plt to plot the point cloud and directly save the picture during the test as we do when infer on KITTI. The code can be slightly modified by yourself to achieve this goal. [code](https://github.com/yuxumin/PoinTr/blob/master/utils/misc.py#L207)

**Comment by yuxumin** [comment]
Close it since no response. Feel free to re-open it if problems still exist
