### ISSUE TITLE
The question about the code of GRNet in this repository.

### ISSUE THREAD

**Issue by duzhenjiang113** [yuxumin/PoinTr#133]
Thanks for your brilliant open-source work. And I have a question about the GRNet. For the input partial point cloud, you multiply by 0.5 in your code. May I ask why you chose to do this? Will this greatly influence the results?
Looking forward to your reply! :-)

**Comment by yuxumin** [comment]
Point clouds in PCN are in [-0.5, 0.5] while point clouds in ShapeNet-55/34 lay in [-1, 1]. 
if we do not multiply 0.5 on coordinates, gridding operation will raise a error.

**Comment by duzhenjiang113** [comment]
> Point clouds in PCN are in [-0.5, 0.5] while point clouds in ShapeNet-55/34 lay in [-1, 1]. if we do not multiply 0.5 on coordinates, gridding operation will raise a error.

Ok， thanks for your reply!!!
