### ISSUE TITLE
Epoch 9/150  train.sh   Line 8 ：30127 killed in training PCN methods（ShapeNet 55）

### ISSUE THREAD

**Issue by Hello-hubKing** [yuxumin/PoinTr#14]
I'm sorry to bother you. Is there not enough memory? If so, how much memory do we need?

**Comment by yuxumin** [comment]
Hi, @Hello-hubKing , the OOM problem may be caused by plotting image on the tensorboard during the validation phase. You can turn it off or decrease the number of samples to be plotted.
Hope it helps :)

**Comment by yuxumin** [comment]
Close it since no response. Feel free to re-open it if problems still exist
