### ISSUE TITLE
Evaluation example on the KITTI benchmark

### ISSUE THREAD

**Issue by blukaz** [yuxumin/PoinTr#15]
When I try to run the evaluation example for the KITTI benchmark the training procedure starts. Shouldn't this start only the evaluation? It could be that I'm missing something out...

Note: I'm running the code in google colab.

![image](https://user-images.githubusercontent.com/19351525/142215909-7420b5c4-5bf1-4bd2-8567-a89b91e9274a.png)
![image](https://user-images.githubusercontent.com/19351525/142216005-6ec4d039-526f-42a0-b94e-54062dd3fd1e.png)

Btw, I added the few lines in the runner.py script, as you suggested in a previous issue, on how to save the dense_points.
![image](https://user-images.githubusercontent.com/19351525/142216501-870cb26f-9b7c-4aa5-9682-03ac7f5205e4.png)

Thank you in advance!

**Comment by yuxumin** [comment]
Hi, @blukaz , you can run the evaluation code by simply adding a line `--test`. The current code you are runing is to finetune a pre-train model (on the PCN) to the PCNCars and prepare to test it on the KITTI

**Comment by blukaz** [comment]
Thanks! I got it now... Btw I've wrongly put the code for saving the point in the run_net module, that's why I wasn't getting the points saved when running the evaluation code

**Comment by yuxumin** [comment]
In fact, during the evaluation of KITTI, the code will save the dense point cloud as a numpy array to `args.experiment_path/vis_result`.

**Comment by yuxumin** [comment]
Close it since no response. Feel free to re-open it if problems still exist
