### ISSUE TITLE
PCN + shapeNet-34 dataset URLs are not available

### ISSUE THREAD

**Issue by nanlliu** [yuxumin/PoinTr#17]
Hi there,

Could u update the urls for the datasets mentioned above?

Much appreciated!
Nan

**Comment by yuxumin** [comment]
@nanlliu Hi, i check the url of ShapeNet-55/34, it seems that it is ok. And i find the url for PCN is not available, which is prepared by the author of GRNet. You can access those data in two ways : 1) process those data by yourself following the structions in [GRNet](https://github.com/hzxie/GRNet/blob/master/README.md#preprocess-the-shapenet-dataset) 2) I will upload processed PCN in next week.

**Comment by yuxumin** [comment]
@nanlliu Hi, i upload the PCN to BaiDuYun first. [here](https://pan.baidu.com/s/1KCoaQLVDKVurAzl-AcbSCg)(code:vsqm).

**Comment by nanlliu** [comment]
thanks! it would be cool if you could provide pretrained models of your baselines as well as instructions of evaluating them.

**Comment by yuxumin** [comment]
Hi @nanlliu, sorry that I can't find the pre-trained weights for my baseline in the ablation study. But i think it is not difficult to reproduce the performance of my baseline. Feel free to reopen this issue if there are still problems during reproducing my baselines.
