### ISSUE TITLE
Question about Eval Chamfer Distance

### ISSUE THREAD

**Issue by andrearosasco** [yuxumin/PoinTr#18]
Hello, when you use the Chamfer Distance to evaluate the model, you multiply its value by 1000. I was wondering what is the reason behind it. I know that Occupancy Network multiplies it by 10 because they are using 1/10 * (maximal edge length) as their unit of distance. Is it something similar?

**Comment by yuxumin** [comment]
@andrearosasco Hi, we multiply its value by 1000 *only* in order to print it (just because it is too small). During the optimization of network, we use the original value of CD.

**Comment by andrearosasco** [comment]
Ok make sense, thank you very much!
