### ISSUE TITLE
Some questions about Paper

### ISSUE THREAD

**Issue by duzhenjiang113** [yuxumin/PoinTr#2]
Hi, Xumin.  It's a great paper and I'm inspired a lot. I have a question about the ablation experiment in the paper. When using the baseline test, the result generated by the query generator is replaced, how do the Dynamic Queries of the Transformer decoder be generated? Thanks a lot.

**Comment by yuxumin** [comment]
We replace the query generator with learnable parameters in the ablation study, which is similar to the practice in DETR.

**Comment by duzhenjiang113** [comment]
> DETR

Thanks for your reply. So, it seems it's a linear projection without max pooling operation. Is my understanding correct or not?

**Comment by duzhenjiang113** [comment]
> We replace the query generator with learnable parameters in the ablation study, which is similar to the practice in DETR.

Thanks for your reply. So, it seems it's a linear projection without max pooling operation. Is my understanding correct or not?

**Comment by yuxumin** [comment]
Not really, the queries are independent of the outputs of the encoder. In that case, outputs of the encoder are only used as the memory of the decoder (cross attention) and produce the coarse center points, while the queries of the decoder are some pre-defined and learnable parameters. You can get more details from DETR pipeline (End-to-End Object Detection with Transformers) .
![DETR_pipeline](https://user-images.githubusercontent.com/29698233/132357203-ca74bb8a-5eaf-4b68-b3da-113fedd361f3.png)

**Comment by duzhenjiang113** [comment]
> Not really, the queries are independent of the outputs of the encoder. In that case, outputs of the encoder are only used as the memory of the decoder (cross attention) and produce the coarse center points, while the queries of the decoder are some pre-defined and learnable parameters. You can get more details from DETR pipeline (End-to-End Object Detection with Transformers) .

Thanks, I'll check it.
