### ISSUE TITLE
Attention Map

### ISSUE THREAD

**Issue by benjaminkelenyi** [yuxumin/PoinTr#23]
Hello, 

First of all, thank you very much for your work.
I'd want to know if the attention map can be seen in any [way](https://github.com/yuxumin/PoinTr/blob/master/models/Transformer.py#L80).

Thanks in advance, 
Benjamin

**Comment by yuxumin** [comment]
Hi,
Thanks for your interest in our work.
You can visualize the attention matrix  by matplotlib.
I find an example code for you. [here](https://stackoverflow.com/questions/29432629/plot-correlation-matrix-using-pandas)
