### ISSUE TITLE
test

### ISSUE THREAD

**Issue by JiangZhenW** [yuxumin/PoinTr#26]
hi，when i test PoinTr on KITTI，i meet a error：worker（pid 27631）is killed by signal：killed. how should i solve it？Thank you very musch

**Comment by yuxumin** [comment]
Hi, this problem usually caused by the limited memory while dataloader try to fetch data.
Set a smaller value for `num_workers` in the dataloader may be the fast solution for you.

**Comment by JiangZhenW** [comment]
thank u very much
