### ISSUE TITLE
'XXdataset is not in the dataset registry'

### ISSUE THREAD

**Issue by WuXiaoxuan99** [yuxumin/PoinTr#27]
hi,I want to use PoinTr in other dataset, and I have already modified the related code but got an error "XXdataset(the new dataset) is not in the dataset registry"？
Could you help me?

**Comment by yuxumin** [comment]
Hi, have you already got the way out of your problem? see [here](https://github.com/yuxumin/PoinTr/issues/11#issuecomment-976423737)

**Comment by WuXiaoxuan99** [comment]
Thank you for your attention! I have solved my problem.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xumin ***@***.***&gt;; 
发送时间: 2022年1月23日(星期天) 中午11:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [yuxumin/PoinTr] &#39;XXdataset is not in the dataset registry&#39; (Issue #27)





 
Hi, have you already got the way out of your problem? see here
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
