### ISSUE TITLE
Visualization 

### ISSUE THREAD

**Issue by Vishalteli** [yuxumin/PoinTr#29]
Can I get the code for Visualization?

**Comment by yuxumin** [comment]
Hi, we visualize the point cloud by Windows Meshlab. See issue [12](https://github.com/yuxumin/PoinTr/issues/12)

**Comment by Vishalteli** [comment]
I'm able to save it as .npy files, how to visualize the .npy file? Or can you suggest how to save it as a txt file and visualize in meshlab.

**Comment by yuxumin** [comment]
Numpy provides a function named `np.savetxt()`, which can solve your problem.

**Comment by Vishalteli** [comment]
![Screenshot (531)](https://user-images.githubusercontent.com/98252158/152675827-ba32eada-2b40-4824-8ab8-bee102070951.png)

If I try to save the dense points in txt file, I'm getting this error. 

ValueError: Expected 1D or 2D array, got 3D array instead

**Comment by Vishalteli** [comment]
The array is a 3d array that cannot be saved as txt file, have you reshaped the array before saving it?
 If I print the shape of dense points array it's (1, 16384, 3)

**Comment by Vishalteli** [comment]
Got It, Thank you
