### ISSUE TITLE
How to collect the coordinates of the points from the completed point cloud?

### ISSUE THREAD

**Issue by LeiKeRrr** [yuxumin/PoinTr#33]
Hi !

I would like to know how I could run the poinTr program on a personnal incompleted point cloud. Also could you help me on the way of collecting the coordinates of the points from the completed point cloud ?

Thank you

**Comment by yuxumin** [comment]
Hi,

1) To train and infer a PoinTr based on your own data, you can follow https://github.com/yuxumin/PoinTr/issues/11#issuecomment-950577364, https://github.com/yuxumin/PoinTr/issues/34#issue-1166613936 to build a new dataset.
2) To generate an incomplete point cloud, I think there are two approaches:
  A. Directly cropping (Flexible, efficient and online) : https://github.com/yuxumin/PoinTr/blob/master/utils/misc.py#L131
  B. Backprojecting depth map from 2.5D to 3D ( A better approximation to the real world scene). https://github.com/wentaoyuan/pcn/tree/master/render

**Comment by LeiKeRrr** [comment]
Hi @yuxumin 

In my previous message I simply meant how to complete an incompleted point cloud file (like an incompleted point cloud of a car) with a pretrained PoinTr model. I am not looking for a training or an evalutation of a PoinTr model. I am a begginer in computer vision and coding in general that's why I am asking (:

**Comment by yuxumin** [comment]
Yeah, i got it. It depends on which pretrained PoinTr you are using:

1) For PoinTr pretrained on ShapeNet55/34, it takes incomplete point clouds with 2048 points as inputs and outputs 8192 points. It requires the point clouds are normalized. as https://github.com/yuxumin/PoinTr/blob/master/datasets/ShapeNet55Dataset.py#L33 (xyz \in [-1, 1]).
2) For PoinTr pretrained on PCN, it takes 2048 points as inputs and outputs 16384 points. It requires the point clouds are normalized as https://github.com/yuxumin/PoinTr/blob/master/datasets/data_transforms.py#L109 (xyz \in [-0.5, 0.5] roughly)

To conclude, make your incompleted point clouds look like the samples in validation/test set (scale, center, number of points, etc.). It will works.

**Comment by LeiKeRrr** [comment]
@yuxumin I am using the Pretrained on ShapeNet55/34. So what is the command to use this model on my point cloud ? Because in the readme file I only saw commands for evaluation and training. 

Also for my project I would like to use a completion program in real time. Is it possible with PoinTr ?

**Comment by yuxumin** [comment]
@LeiKeRrr 

Inferencing on the given data has not been implemented. There are mainly a few steps, you can try it yourself:
1) Load the pretrained PointTr
2) Load the data you want to complete. Don't forget to transform the data to the required format (shape is [B, 2048, 3], xyz in [-1, 1])
3) Feed the data to PoinTr, obtaining the complete point clouds.

As for real-time inference, the current PoinTr can process about 50 point clouds per second. If you want to make it faster. I think you can modify PointTr slightly, and train a PoinTr by yourself:
1) Use shallow encoders and decoders.
2) Replace the last FoldingNet with a simple FC

**Comment by LeiKeRrr** [comment]
Thank you for all your advice. Now I understand this better, thank you (: I'll let you know if I get stuck

**Comment by LeiKeRrr** [comment]
Hi @yuxumin !

I am trying to crop a point cloud with this : https://github.com/yuxumin/PoinTr/blob/master/utils/misc.py#L131

Could you explain to me what is the B in [B,2048,3]. Also, I don't understant what is the type and the purpose of the crop parameter.

**Comment by yuxumin** [comment]
Hi, @LeiKeRrr 

1) `B` is the batch_size. An input with shape [B 2048 3] contains `B` point clouds, and each point cloud consists of 2048 points. Each point is represented by (x, y, z).
2) For the function in https://github.com/yuxumin/PoinTr/blob/master/utils/misc.py#L131. The first input parameter `xyz` is the complete point clouds with shape [B N 3], where `N` represents the number of points in complete point clouds. The second input parametr `num_points` is the aforementioned `N`.   The third parameter `crop` is the number of points you want to crop out.  As for the last two parameters, `fixed_points` is the view point you want to fix. If `fixed_points = none`, this function will randomly choose a viewpoint. `padding_zeros` indicates whether to pad cropped points with zero.

**Comment by LeiKeRrr** [comment]
Ok I see. Then, when I tried to run the code I have this error : 


```
  File "C:\Users\peter\OneDrive\Bureau\CodePoinTr\Open3dCodes\GenerateFinalPointCloud.py", line 48, in seprate_point_cloud
    points = points.unsqueeze(0)

AttributeError: 'numpy.ndarray' object has no attribute 'unsqueeze'
```

It means that xyz has to be a tensor ?

**Comment by yuxumin** [comment]
Yes, the type of xyz should be `torch.tensor`. Or you can modify the code to make it work on numpy array.

**Comment by LeiKeRrr** [comment]
Hi @yuxumin ! 

I am trying to load the pretrained model and then feed my data to PoinTr. I intend to do something like that but I am not really sure :

```
model = PoinTr()
model.load_state_dict(torch.load('PretrainedModel.pth'))
model.eval()
```
Could you tell me if my approach is correct ?

**Comment by yuxumin** [comment]
Yeah, it is correct. Don't forget specify the `config` for PoinTr, like:
```
from easydict import EasyDict
model_config = EasyDict(
    num_pred = 14336, 
    num_query = 224, 
    knn_layer = 1, 
    trans_dim = 384,
)
model = PoinTr(config)
...
```

**Comment by LeiKeRrr** [comment]
Hi @yuxumin ! Sorry to disturb you again. 

I am trying to load properly the pretrained model as I explained in my previous message but I get the following error : 

```
RuntimeError: Error(s) in loading state_dict for PoinTr:
	Missing key(s) in state_dict: "base_model.grouper.input_trans.weight", "base_model.grouper.input_trans.bias",...
```
So I tried with your function load_model(base_model,ckpt_path) but I have this error : 

```
RuntimeError: Error(s) in loading state_dict for PoinTr:
	size mismatch for base_model.coarse_pred.2.weight: copying a param with shape torch.Size([288, 1024]) from checkpoint, the shape in current model is torch.Size([672, 1024]).
	size mismatch for base_model.coarse_pred.2.bias: copying a param with shape torch.Size([288]) from checkpoint, the shape in current model is torch.Size([672]). 
```
The shape of my input point cloud is (1,2048,3) and my code : 

```
model_config = EasyDict(
    num_pred = 14336, 
    num_query = 224, 
    knn_layer = 1, 
    trans_dim = 384,
)
model = PoinTr(model_config)
if torch.cuda.is_available():
    model.cuda()

load_model(model, 'C:\Repos\PoinTr-master\pretrained\PoinTr_ShapeNet55.pth') #the error appears here
model.eval()
fichiercrop = fichiercrop.type(torch.cuda.FloatTensor)
ret = model(fichiercrop)
```

Could you explain to me how to fix this error ? Thank you

**Comment by yuxumin** [comment]
Hi, @LeiKeRrr , That's because the models are different for ShapeNet-55 and PCN. (different `num_query` and `num_pred`). If you want to use the weight pretrained on ShapeNet-55, please use the config from https://github.com/yuxumin/PoinTr/blob/master/cfgs/ShapeNet55_models/PoinTr.yaml#L31. Or load the PoinTr pretrained on PCN.

**Comment by LeiKeRrr** [comment]
Hi @yuxumin ! 

Thank you so much for all your help it worked !

**Comment by 8umpk1n** [comment]
> 感谢您的所有建议。现在我更好地理解了这一点，谢谢（：如果我卡住了，我会告诉你
hi，Have you fulfilled your wish for real-time completion?
