### ISSUE TITLE
How can i fix the error clamed "ModuleNotFoundError: No module named 'chamfer'"?

### ISSUE THREAD

**Issue by Jimmybear-123** [yuxumin/PoinTr#35]
HI! Thank you for your open source! I am trying to run examples you written in your document, but after input the code, it remind me an error named "ModuleNotFoundError: No module named 'chamfer'". How can I fix it?  Looking for your help.

**Comment by yuxumin** [comment]
Hi, 

This issue can be solved by installing extensions again, details can be found in https://github.com/yuxumin/PoinTr/issues/6

**Comment by Jimmybear-123** [comment]
Thank you for your reply! I have tried #6, run "python setup.py install --user" in /extensions/chamfer_dist/. I back to the /PoinTr-master/ and run the terminal. I input "bash install.sh", and I try run"bash ./scripts/test.sh 0 \
    --ckpts ./pretrained/PoinTr_ShapeNet55.pth \
    --config ./cfgs/ShapeNet55_models/PoinTr.yaml \
    --mode easy \
    --exp_name example"
But the prompt is still the same. No module named 'chamfer'
I am confused, and Looking for your help.
Thank you.

**Comment by yuxumin** [comment]
This is weird, the same problem can be solved with this situation before.
Could you create a new virtual env and try it again?

**Comment by Jimmybear-123** [comment]
Thank you for your reply! I solved this error. I delete whole project, and do it again, this error was gone. But There's another error. Nijia is required to load C++ extensions. And I am working on it.

**Comment by Jimmybear-123** [comment]
Oh, thank you! I run "sudo apt install ninja-build", and the problem has been solved!

**Comment by JiangZhenW** [comment]
hi, your work is very wonderful, and i an really interested in it. but i meet a problem: no module named 'pointnet2_ops',how can i solve it? thanks a lot!

**Comment by yuxumin** [comment]
@JiangZhenW  Have your installed the dependency of pointnet?
```
pip install "git+git://github.com/erikwijmans/Pointnet2_PyTorch.git#egg=pointnet2_ops&subdirectory=pointnet2_ops_lib"
```

**Comment by JiangZhenW** [comment]
Excuse me, does the module pointnet2_ops is build by compling? i can not pip install the address that you gived successful, the error is:no matching distribution found for pointnet2-ops(unavailable)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuxumin/PoinTr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月22日(星期二) 晚上8:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuxumin/PoinTr] How can i fix the error clamed "ModuleNotFoundError: No module named 'chamfer'"? (Issue #35)





 
@JiangZhenW  Have your installed the dependency of pointnet?
 pip install "git+git://github.com/erikwijmans/Pointnet2_PyTorch.git#egg=pointnet2_ops&amp;subdirectory=pointnet2_ops_lib"

**Comment by yuxumin** [comment]
Hi, could you try to build it from source and see if it will work for you (ref: https://github.com/erikwijmans/Pointnet2_PyTorch)
