### ISSUE TITLE
The program is killed by the system

### ISSUE THREAD

**Issue by Starak-x** [yuxumin/PoinTr#37]
![image](https://user-images.githubusercontent.com/71073947/158289567-925118e8-b822-406e-aee7-4ffd521711db.png)

**Comment by Starak-x** [comment]
./scripts/train.sh: row 8: 20954 was killed

**Comment by yuxumin** [comment]
Hi, 

Is it the experiment on ShapeNet-55? It seems that the code is killed due to the memory issue. I recommend to decrease the number of point clouds shown in tensorboard.
You can modify https://github.com/yuxumin/PoinTr/blob/master/tools/runner.py#L215 to (for example)
```
if val_writer is not None and idx % 2000 == 0:
```

**Comment by yuxumin** [comment]
Close it since no response. Feel free to re-open it if problems still exist
