### ISSUE TITLE
Could not find a version that satisfies the requirement pointnet2-ops 

### ISSUE THREAD

**Issue by XiaoyanQian** [yuxumin/PoinTr#39]
Hi Yuxumin,
It is great work, indeed. i caught this error when I run the code of pip install "git+git://github.com/erikwijmans/Pointnet2_PyTorch.git#egg=pointnet2_ops&subdirectory=pointnet2_ops_lib". I was wondering if you could help me in that regard. Thank you so much and any response will be highly appreciated. Stay safe

Error listed as follows:
WARNING: Ignoring invalid distribution -orch (/home/mnt/xyqian/miniconda3/envs/centernet/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution -orch (/home/mnt/xyqian/miniconda3/envs/centernet/lib/python3.8/site-packages)
Collecting pointnet2_ops
  Cloning git://github.com/erikwijmans/Pointnet2_PyTorch.git to /tmp/pip-install-kg2drmx2/pointnet2-ops_31824b8057754e00b827bd29dca8a98c
  Running command git clone -q git://github.com/erikwijmans/Pointnet2_PyTorch.git /tmp/pip-install-kg2drmx2/pointnet2-ops_31824b8057754e00b827bd29dca8a98c
  fatal: remote error:
    The unauthenticated git protocol on port 9418 is no longer supported.
  Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
WARNING: Discarding git+git://github.com/erikwijmans/Pointnet2_PyTorch.git#egg=pointnet2_ops&subdirectory=pointnet2_ops_lib. Command errored out with exit status 128: git clone -q git://github.com/erikwijmans/Pointnet2_PyTorch.git /tmp/pip-install-kg2drmx2/pointnet2-ops_31824b8057754e00b827bd29dca8a98c Check the logs for full command output.
**ERROR:** Could not find a version that satisfies the requirement pointnet2-ops (unavailable) (from versions: none)
**ERROR:** No matching distribution found for pointnet2-ops (unavailable)
WARNING: Ignoring invalid distribution -orch (/home/mnt/xyqian/miniconda3/envs/centernet/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution -orch (/home/mnt/xyqian/miniconda3/envs/centernet/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution -orch (/home/mnt/xyqian/miniconda3/envs/centernet/lib/python3.8/site-packages)

**Comment by yuxumin** [comment]
Hi! yes, i see. I notice this problem in other issue (https://github.com/yuxumin/PoinTr/issues/35#issuecomment-1076126460). Could you try to build it from the source codes according to the instructions in the original repo (https://github.com/erikwijmans/Pointnet2_PyTorch#building-only-the-cuda-kernels)？ Looking forward to your reply.

**Comment by yuxumin** [comment]
Close it since no response. Feel free to re-open it if problems still exist
