### ISSUE TITLE
How to evaluate KITTI dataset under the Fidelity and MMD metrics?

### ISSUE THREAD

**Issue by beibeirory** [yuxumin/PoinTr#4]
Thanks for you work. 
I have a question that how to evaluate KITTI dataset under the Fidelity and MMD metrics?

**Comment by yuxumin** [comment]
I will take the time to update the evaluation code on KITTI dataset.

**Comment by yuxumin** [comment]
Hi, the evaluation code on KITTI dataset is updated.  Hope it helps :)

**Comment by beibeirory** [comment]
Thanks very much. @yuxumin

**Comment by JiangZhenW** [comment]
> Hi, the evaluation code on KITTI dataset is updated. Hope it helps :)

excuse me, if the MMD metric could consume a lot of time? when i want to test this metric, the pycharm show it will spend more than 100 hours? is there a way to speed it up?
