### ISSUE TITLE
Why use FoldingNet to do upsampling?

### ISSUE THREAD

**Issue by Starak-x** [yuxumin/PoinTr#44]
Hi, Xumin. It's a great paper and I'm inspired a lot. I have a question about upsampling part in the paper. Why use FoldingNet to do upsampling? Thanks a lot.

**Comment by yuxumin** [comment]
Hi, Xing. Thanks for your interest in our work.
We reconstruct the point cloud in a coarse-to-fine manner. The FoldingNet is adopted to reconstruct a more detailed local structure around a given center (in other word, as you say, it acts as a upsampling part) . 
In the very begining, we have a prior knowledge that FoldingNet is a better choice than MLPs in point cloud reconstructing tasks.  However, someone finds that replacing the FoldingNet with a MLP in our PoinTr can still work well but requires less FLOPs and runs faster.
