### ISSUE TITLE
How to set encoder_feature in PCN_models/TopNet.yaml?

### ISSUE THREAD

**Issue by whuhxb** [yuxumin/PoinTr#46]
Hi, how to set encoder_feature in PCN_models/TopNet.yaml?  As I run  bash ./scripts/train.sh 2   --config ./cfgs/PCN_models/TopNet.yaml    --exp_name example

I met the error like this:

in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AttributeError: TopNet: 'EasyDict' object has no attribute 'encoder_feature'

**Comment by yuxumin** [comment]
Hi,
Change `encoder_channel` in https://github.com/yuxumin/PoinTr/blob/master/cfgs/PCN_models/TopNet.yaml#L23 to `encoder_feature`.

**Comment by whuhxb** [comment]
@yuxumin  OK. Can run. But I still met OOM.
