### ISSUE TITLE
OOM even when reducing batch size!

### ISSUE THREAD

**Issue by Mona-ShZeinoddin** [yuxumin/PoinTr#47]
Hello and congrats on the excellent work!

I am trying to train the model with 2 gpus:

CUDA_VISIBLE_DEVICES=0,1 bash ./scripts/dist_train.sh 2 13232 \
    --config ./cfgs/PCN_models/PoinTr.yaml \
    --exp_name example

I am using two Nvidia 1080Tis, it would give me the error of running out of memory. I tried reducing the batchsize from 48 to 24 and even 12, but still the problem remains. do you have any solutions in mind?
thnx

**Comment by yuxumin** [comment]
Sorry, i have no idea what's the problem now. Did you use the default config file provided by this repo? Are other networks work well in your server?

**Comment by Mona-ShZeinoddin** [comment]
No there are no other networks and yes at first I used the default configs and then I just change d the batch size and reduced it

**Comment by yuxumin** [comment]
That's weird. Could you successfully train a PCN (change `--config ./cfgs/PCN_models/PoinTr.yaml` to `--config ./cfgs/PCN_models/PCN.yaml`？

**Comment by yuxumin** [comment]
Close it since no response. Feel free to re-open it if problems still exist
