### ISSUE TITLE
Opinion about point cloud completion 

### ISSUE THREAD

**Issue by LeiKeRrr** [yuxumin/PoinTr#52]
Hi @yuxumin ! 

I had a question about point cloud completion for a real application. I have created a point cloud from a real car and I am trying to complete it thanks to the pretrained model on ShapeNet-55 dataset. However, the result is not really satisfactory, as shown with the pictures below :
![car](https://user-images.githubusercontent.com/88313194/167283491-cc41778d-7232-40a8-ab5d-a1db6d393dc9.png)
 
And this is the result after completion : 
![car2](https://user-images.githubusercontent.com/88313194/167283517-a6cdc396-8bfd-443f-964b-384bc9da6858.png)

I have checked the input format and also the config for poinTr. Do you know what is wrong or what I could do to improve the completion ? Have you ever had experiences or feedback with point cloud completion for real applications ? 

Thanks

**Comment by yuxumin** [comment]
Hi,

The input point cloud seems to be the head of the car? Have you checked the scale of the input point cloud? I see the predicted point cloud around the front of the car.

I have two idea which may work:
- Normalize the input point cloud of the car. (centering and scaling it according to the training samples of the pretrained PoinTr. ShapeNet55 is roughly [-1, 1], PCN is roughly [-0.5, 0.5])
- Using PointTr for KITTI

**Comment by LeiKeRrr** [comment]
Hi,

Thank you for your answer. 

Yes, it is the head of the car. The points are already normalized I forgot to mention that, sorry.

I will try using PointTr for KITTI and let you know

**Comment by LeiKeRrr** [comment]
Hi ! 

I tried with the pretrained KITTI model with no success. My input point cloud was normalized with points included in [-1,1]. 

I was also wondering if the orientation of the car does matter ? Because in my case the car is almost upside-down compared to the orientation of dataset models.
