### ISSUE TITLE
About F1 score

### ISSUE THREAD

**Issue by AllenXiangX** [yuxumin/PoinTr#63]
Hi, thanks for sharing the amazing work. 
I have a question about F1 score listed in the paper. Is the F1 on ShapeNet34 an averaged score across the three difficulty degrees or is it just from a single difficulty level such as Simple?

**Comment by yuxumin** [comment]
Hi, it is the averaged F1-score across three DD.

**Comment by AllenXiangX** [comment]
Thanks for the reply!

**Comment by CRISZJ** [comment]
hello,  about F-Score@1%. Does 1% mean the threshold?

**Comment by yuxumin** [comment]
@CRISZJ Yep
