### ISSUE TITLE
The Version of ShapeNet for ShapeNet55/34

### ISSUE THREAD

**Issue by wulalala1999** [yuxumin/PoinTr#66]
Hi @yuxumin,
    Thanks for your contributions to build new benchmarks ShapeNet55/34. I have a question about the datasets. There two versions of shapenet_core on the official website. So, what's the version you choiced for ShapeNet55/34?

**Comment by yuxumin** [comment]
Hi, we use ShapeNetCore.V2

**Comment by wulalala1999** [comment]
Thanks for your reply. By the way, in PointBert, I use the linearSVM on nvidia 3090 successfully during the pretrain. You can see this comment. (https://github.com/lulutang0608/Point-BERT/issues/13)
