### ISSUE TITLE
about assign GPU

### ISSUE THREAD

**Issue by JiangZhenW** [yuxumin/PoinTr#67]
hi, your work is wonderful! 
if i want to assign gpu through ‘Edit Configurations’ in pycharm , how should i do?
for example i have 4 gpus, but i just need to use 2 gpus.
thank your very much!

**Comment by yuxumin** [comment]
```
bash ./scripts/train.sh <GPUIDS> \
    --config <config> \
    --exp_name <name> \
    [--resume] \
    [--start_ckpts <path>] \
    [--val_freq <int>]
```
For example: bash ./scripts/train.sh 0,1 --config ./cfgs/PCN_models/PoinTr.yaml  --exp_name example, To use GPU:0 and GPU:1 to train a PoinTr on PCN.

**Comment by JiangZhenW** [comment]
yes, i know your means, but i would like to use pycharm and run main.py instead of use the terminal.
thank you for your reply
