### ISSUE TITLE
For Point Cloud Challenge 2021 on Completion and Registration

### ISSUE THREAD

**Issue by JiangZhenW** [yuxumin/PoinTr#68]
Congratulations on winning the first place in the competition, I notice that you add the RENet on your basis network. Could you give some specific message about the inpout of the RENet? The input of point is the final rebuilded point in your work? And what is the input of feature to the RENet? Thank you

**Comment by yuxumin** [comment]
Thank for your interest in our work.
Yes, we input the final rebuilt point cloud into RENet, the feature is the global feature of Transformer Encoder.

**Comment by JiangZhenW** [comment]
Thank you.
by the way，the final rebuilt point cloud has 8192 points？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuxumin/PoinTr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月28日(星期四) 中午12:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuxumin/PoinTr] For Point Cloud Challenge 2021 on Completion and Registration (Issue #68)





 
Thank for your interest in our work.
 Yes, we input the final rebuilt point cloud into RENet, the feature is the global feature of Transformer Encoder.

**Comment by yuxumin** [comment]
In MVP, final rebuilt point cloud contains 3072 points (2048 input +1024 predicted)

**Comment by JiangZhenW** [comment]
thank you for your reply.






------------------ 原始邮件 ------------------
发件人: "Xumin ***@***.***&gt;; 
发送时间: 2022年7月28日(星期四) 中午12:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yuxumin/PoinTr] For Point Cloud Challenge 2021 on Completion and Registration (Issue #68)





 
In MVP, final rebuilt point cloud contains 3072 points (2048 input +1024 predicted)
