### ISSUE TITLE
Ask for pretrained models of GRNet and PCN

### ISSUE THREAD

**Issue by xinze98** [yuxumin/PoinTr#73]
Would you please offer the models of GRNet and PCN pretrained in ShapeNet55 dataset?

**Comment by yuxumin** [comment]
I am sorry that the ckpts of these two models are lost during last time i reinstalled ubuntu of my personal pc.

**Comment by xinze98** [comment]
> I am sorry that the ckpts of these two models are lost during last time i reinstalled ubuntu of my personal pc.

It's okay. Thank you all the same.
