### ISSUE TITLE
about CD for PCNDataset

### ISSUE THREAD

**Issue by JiangZhenW** [yuxumin/PoinTr#74]
Thank you for your work!
I notice that you fixed a bug in datasets/PCNDataset.pyhttps://github.com/hzxie/GRNet/pull/27, and update the performance of PoinTr on PCN benchmark (CD from 8.38 to 7.26).
But i find this bug is about GRNet, not PoinTr, do i make some mistakes?
thank you

**Comment by yuxumin** [comment]
Hi,
We build our project based on GRNet. So in the beginning, PoinTr shares this bug.
