### ISSUE TITLE
ModuleNotFoundError: No module named 'chamfer'

### ISSUE THREAD

**Issue by Albert337** [yuxumin/PoinTr#75]
hello,at first of all,thanks for your  greate works.But when i test your code with scripts for ShapeNet55,i meet the error obove! i have finished the script `bash install.sh`,and it generate four folders like chamfer_dist.And then i try to extrat the file from "chamfer_dist/dist" and put in "chamfer_dis",but the error cannot be fixed! Is there any advice?Thanks again!

**Comment by yuxumin** [comment]
see https://github.com/yuxumin/PoinTr/issues/6
