### ISSUE TITLE
This problem occurs when I try the following command line

### ISSUE THREAD

**Issue by xiaoxuetulws** [yuxumin/PoinTr#76]
bash ./scripts/test.sh <GPU_IDS>  \
    --ckpts <path> \
    --config <config> \
    --exp_name <name> \
    [--mode <easy/median/hard>]

The problem     bash: GPU_IDS: No such file or directory
How can I solve this problem?

**Comment by yuxumin** [comment]
Hi,
Use a specific gpu_id according to your server.
For example:
```
bash ./scripts/test.sh 0 --ckpts xxx.pth --config xxx.yaml --exp_name xxxx
```

**Comment by xiaoxuetulws** [comment]
> 

thinks

**Comment by xiaoxuetulws** [comment]
> 嗨， 根据您的服务器使用特定的 gpu_id。 例如：
> 
> ```
> bash ./scripts/test.sh 0 --ckpts xxx.pth --config xxx.yaml --exp_name xxxx
> ```
thanks
