### ISSUE TITLE
ImportError: /home/cky/anaconda3/envs/python37/lib/python3.7/site-packages/knn_cuda/csrc/_ext/knn/knn.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by chky1997** [yuxumin/PoinTr#8]
Hi, I have run the building commands, but when I run the first example training command the error shows like this. The KNN cuda 0.2 is installed. Could you please give me some advice?

**Comment by yuxumin** [comment]
See  [here](https://github.com/unlimblue/KNN_CUDA/issues/2#issuecomment-494279237)

**Comment by Greywan** [comment]
> I noticed that Ninja should also be installed, is that right?
if "Ninja is required to load C++ extensions"
you can try to run:
`wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip`
`sudo unzip ninja-linux.zip -d /usr/local/bin/`
`sudo update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force`

**Comment by yuxumin** [comment]
Close it since no response. Feel free to re-open it if problems still exist.
