### ISSUE TITLE
训练真实数据集

### ISSUE THREAD

**Issue by ao216** [yuxumin/PoinTr#85]
您好！我留意到shapeNet数据集和PCN数据集的坐标皆进行了居中且归一化操作。实际运用中，对于真实世界分割出来的坐标不居中且不归一化的单体，我需要如何修改该框架，实现点云补齐呢？
提前感谢！

**Comment by yuxumin** [comment]
您好，这个问题目前其实还是一个在实际运用中的问题。如果一定要解决这个问题，可以参考KITTI补全的流程，3d det -> predict bboxes for objects -> crop and resize -> complete.

**Comment by ao216** [comment]
我尝试一下，十分感谢
