### ISSUE TITLE
a bug while resume

### ISSUE THREAD

**Issue by Starak-x** [yuxumin/PoinTr#90]
Hi, Xumin. Thanks for your splendid work, it inspires me a lot. But I find a bug while resuming. The code would be killed by the system
![image](https://user-images.githubusercontent.com/71073947/214872177-ea2fb98f-4006-423e-a673-c327a8ec4e2a.png)
Then I use "--resume" to resume it. I find the learning rate is not correct.(My initial learning rate is 0.0002)
![image](https://user-images.githubusercontent.com/71073947/214873112-290a79f8-bbca-47ab-9c22-3bacd129d5b6.png)
![image](https://user-images.githubusercontent.com/71073947/214873315-1e0d4c0c-3974-4bca-b829-c68d3d06fdd7.png)

**Comment by yuxumin** [comment]
Hi, thanks for you interest in our work. 
Can you take a look into this bug and then raise a pull request.

**Comment by Starak-x** [comment]
I find that scheduler is not resume. Take 'last_epoch' into consideration for StepLR, LambdLR can solve this problem. CosLR does not need to be modified.
builder.py
![image](https://user-images.githubusercontent.com/71073947/215237433-198a7597-5ba2-4b07-870f-898e596baba4.png)
![image](https://user-images.githubusercontent.com/71073947/215237688-e4824cf5-352f-4806-82d4-910a5fb40e97.png)
misc.py
![image](https://user-images.githubusercontent.com/71073947/215237789-080b90fd-a220-4b10-b5df-d034a97d53fc.png)
runner.py
![image](https://user-images.githubusercontent.com/71073947/215237836-d7df783f-9498-409c-910b-1aa8221d54ef.png)

**Comment by wra187611** [comment]
have you solved the problem?

**Comment by Starak-x** [comment]
> 

Yes, I solved it. I modified 'last_epoch' to resume learning rate.

**Comment by Starak-x** [comment]
> have you solved the problem?

Yes, I solved it. I modified 'last_epoch' to resume learning rate.

**Comment by Starak-x** [comment]
> have you solved the problem?

Yes, I solved it. I modified 'last_epoch'  in the code aforementioned to resume learning rate

**Comment by Starak-x** [comment]
Yes, I solved it. I modified 'last_epoch' in the aforementioned code to resume learning rate.

**Comment by yuxumin** [comment]
The code is updated in 7b411c2aa50412f3c7b65923104681c05fe9e38e

**Comment by Starak-x** [comment]
> have you solved the problem?

Yes, I solved it. I modified 'last_epoch' in aforementioned code to resume learning rate.
