### ISSUE TITLE
关于数据集的一些问题

### ISSUE THREAD

**Issue by xiaoxuetulws** [yuxumin/PoinTr#94]
您好，我在转换.npy文件时出现了一些问题，我想知道关于数据集，您是怎样生成的.npy文件，是直接将图片转换的还是转换的.bin文件，reshape是（-1，3）吗？

**Comment by yuxumin** [comment]
是用render渲染不同角度的depth map，然后通过这个depth map反投影的点云，shape是你说的没错

**Comment by xiaoxuetulws** [comment]
我想请问一下你们是怎么处理的KITTI的数据集使用的呢？
