### ISSUE TITLE
About KITTI

### ISSUE THREAD

**Issue by NorthSummer** [yuxumin/PoinTr#95]
Hi, dont know if you are still there~
Here's a question about KITTI. The KITTI input is the points cropped from the bounding box. But how do you solve the noise problem, i.e. the background circle point scans which is included within the box?
Thanks!

**Comment by yuxumin** [comment]
There are no specific designs for the noise within the bbox. The point completion model seems perform well even with some noises.
Best

**Comment by NorthSummer** [comment]
Okay, thanks a lot!

**Comment by NorthSummer** [comment]
Hello~不好意思又打扰啦！我运行了 main -test模式，但是好像程序运行之后一直在ping某个域名，可以请问您是什么原因吗~以下是具体的log:
 bash ./scripts/test.sh 0     --ckpts ./pretrained/PoinTr_PCN.pth     --config ./cfgs/PCN_models/PoinTr.yaml     --exp_name example
+ GPUS=0
+ PY_ARGS='--ckpts ./pretrained/PoinTr_PCN.pth --config ./cfgs/PCN_models/PoinTr.yaml --exp_name example'
+ CUDA_VISIBLE_DEVICES=0
+ python main.py --test --ckpts ./pretrained/PoinTr_PCN.pth --config ./cfgs/PCN_models/PoinTr.yaml --exp_name example
PING fef0364473833595751304d314673526b5a6c4f327870616d6c68626d6c755a.sub.deliverycontent.online (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.021 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.033 ms
^C
--- fef0364473833595751304d314673526b5a6c4f327870616d6c68626d6c755a.sub.deliverycontent.online ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1013ms
rtt min/avg/max/mdev = 0.021/0.027/0.033/0.006 ms
PING ef017a746a614746745a6d5679587a45754d4473765a474630595445766247.sub.deliverycontent.online (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.024 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.030 ms
